include:
  - project: computing/gitlab-ci-templates
    file:
      - python.yml

stages:
  - initial
  - test
  - docs

precommit:
  stage: initial
  extends:
    - .python:base
  script:
    - pip install pre-commit
    - pre-commit run --all-files --verbose --show-diff-on-failure

integration-test:
  stage: test
  extends:
    - .python:base
  script:
    - pip install jsonschema
    - jsonschema -i tests/cbc-meta-data-example.json schema/cbc-meta-data-v1.schema

unit-test:
  stage: test
  extends:
    - .python:pytest
  script:
    - pip install -r requirements.txt
    - pip install .
    - pytest --cov cbcflow --cov-report xml

schema-html:
  stage: docs
  extends:
    - .python:base
  script:
    - python -m pip install -r requirements.txt
    - cd schema/visualization/.build/
    - generate-schema-doc ../../cbc-meta-data-v1.schema ../cbc-meta-data-schema.html
    - cd ../../../
  artifacts:
    paths:
    - schema/visualization/*
    - schema/visualizatoin/.build/*