include:
  - project: computing/gitlab-ci-templates
    file:
      - python.yml

stages:
  - initial
  - test
  - docs
  - deploy

precommit:
  stage: initial
  extends:
    - .python:base
  script:
    - pip install pre-commit
    - pre-commit run --all-files --verbose --show-diff-on-failure

integration-test:
  stage: test
  extends:
    - .python:base
  script:
    - pip install jsonschema
    - jsonschema -i tests/cbc-meta-data-example.json schema/cbc-meta-data-v1.schema

unit-test:
  stage: test
  extends:
    - .python:pytest
  script:
    - pip install -r requirements.txt
    - pip install .
    - pytest --cov cbcflow --cov-report xml

schema-html:
  stage: docs
  extends:
    - .python:base
  script:
    - python -m pip install -r requirements.txt
    - mkdir schema/visualization
    - cd schema/visualization/
    - generate-schema-doc ../cbc-meta-data-v1.schema cbc-meta-data-schema.html
    - cd ../..
  artifacts:
    paths:
    - schema/visualization/*

docs:
  stage: docs
  extends:
    - .python:base
  script:
    - python -m pip install -r requirements.txt
    - pip install .
    - cd docs/
    - python -m pip install -r requirements.txt
    - make html
  artifacts:
    paths:
      - docs/_build/html/

pages:
  stage: deploy
  script:
    - mkdir public/
    - mv schema/visualization/* public/
    - mv docs/_build/html/* public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - main
