# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.3.4.dev36+gcbcf5a9.d20230414"
__version_tuple__ = version_tuple = (0, 3, 4, "dev36", "gcbcf5a9.d20230414")
